services:
  backend:
    image: bohuang910407/chatgpt_react_django-backend:latest
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: bohuang910407/chatgpt_react_django-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 